spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;
    username: sa
    password:
  jpa:
    show-sql: true

jwt:
  secret:
    key : MjAyMjEyMDbsiqTtlITrp4HrtoDtirjsiJnroKjso7zssKjqs7zsoJzrpbzsnITtlZxKV1Trpbzrp4zrk6TslrTrtIXsi5zri6Qu